fix: Removed retry loop to fix issue where SDK receives previous PUBACK.
moderepo/device-sdk-go pull request #21
Opened 2019-08-28 07:28 UTC by takeshinoda

Fixed issue is the following.

There is possible that PUBACK of 2nd and 3rd PUBLISH remain in the channel of PUBACK after the selecting loop. Next the selecting loop retry it does not wait until timed out. So, this loop high frequency retry because it does not wait timeout. The channel of PUBACK accumulates PUBACK more frequently.

2019-08-28 07:32 UTC, takeshinoda commented on mqtt.go
> -	for count := uint(1); count <= maxDeviceEventAttempts; count++ {
Remove retry.

2019-08-28 07:32 UTC, takeshinoda commented on mqtt.go
> +		mc.reportError(fmt.Errorf("event delivery timeout: %s", msg))
Call `reportError` for reconnect if it is timeout until wait for `PUBACK`. Because, MQTT connection is not stable in this situation.

2019-08-28 07:32 UTC, takeshinoda commented on mqtt.go
> +		mc.reportError(fmt.Errorf("event delivery unmatched Ack Packet: %s", msg))
In the same way, call reportError for reconnect if it received another packet id. Because, MQTT connection is not stable in this situation.

2019-08-28 07:32 UTC, takeshinoda commented on core.go
> +	syncedBuldDataRetryInterval = time.Second * 15
Stretch timeout.

2019-08-28 07:32 UTC, takeshinoda commented on core.go
> -	maxDeviceEventAttempts      uint = 3
Removed retry.

2019-08-28 07:46 UTC, reprimande approved these changes
LGTM

2019-08-28 22:38 UTC, ethankan requested changes

2019-08-28 22:38 UTC, ethankan commented on core.go
> +	syncedBuldDataRetryInterval = time.Second * 15
```suggestion
	syncedBulkDataRetryInterval = time.Second * 15
```

2019-08-28 22:38 UTC, ethankan commented on core.go
> +// Depricated: Use ConfigureDeveiceEventTimeout
```suggestion
// Deprecated: Use ConfigureDeviceEventTimeout
```

2019-08-28 22:38 UTC, ethankan commented on core.go
> +func ConfigureDeveiceEventTimeout(retryInterval time.Duration) {
```suggestion
func ConfigureDeviceEventTimeout(retryInterval time.Duration) {
```

2019-08-28 22:38 UTC, ethankan commented on mqtt.go
> +	case <-time.After(syncedBuldDataRetryInterval):
```suggestion
	case <-time.After(syncedBulkDataRetryInterval):
```

2019-08-28 23:59 UTC, takeshinoda commented on core.go
> +	syncedBuldDataRetryInterval = time.Second * 15
Oh.... Thank you><

2019-08-29 05:23 UTC, takeshinoda commented
@ethankan fixed  🙇

2019-08-29 06:06 UTC, ethankan approved these changes

2019-09-03 10:15 UTC, takeshinoda commented
I've completed long run test. So, I've confirmed almost stable running.

2019-09-03 10:15 UTC, merged