v3 of the module
moderepo/device-sdk-go pull request #33
Opened 2020-02-12 08:54 UTC by shigmas

To avoid confusion, since this is a rewrite, we will keep development on the v2 module simultaneously. This allows us to have a master branch were we can easily see both v2 and v3 modules.
Tweaks to run with v3

Most of the code was v3, so just a few more changes to get all the versions correct.

For reference, the previous PR:
https://github.com/moderepo/device-sdk-go/pull/27

2020-03-05 01:13 UTC, takeshinoda approved these changes
Thank you for your great working!!

2020-03-06 03:38 UTC, ethankan requested changes
My only request is to update the README a little bit.

2020-03-06 03:38 UTC, ethankan commented on v3/README.md
> +[![GoDoc](https://godoc.org/github.com/moderepo/device-sdk-go?status.svg)](https://godoc.org/github.com/moderepo/device-sdk-go)
Need to update this link?

2020-03-06 03:38 UTC, ethankan commented on v3/README.md
> +See the full API documentation [here](https://godoc.org/github.com/moderepo/device-sdk-go).
And this?

2020-03-10 11:04 UTC, shigmas commented on v3/README.md
> +See the full API documentation [here](https://godoc.org/github.com/moderepo/device-sdk-go).
points to v3 now

2020-03-17 01:40 UTC, ethankan approved these changes

2020-03-17 03:18 UTC, merged